import type { Metadata } from 'next'
import SideBar from './_component/SideBar'

export const metadata: Metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return <SideBar>{children}</SideBar>
}
