import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { AntdRegistry } from '@ant-design/nextjs-registry'
import dynamic from 'next/dynamic'
import { LoadingProvider } from './context/LoadingContext'

const GlobalLoading = dynamic(() => import('@/components/GlobalLoading'), { ssr: false })

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <LoadingProvider>
          <GlobalLoading />
          <AntdRegistry>{children}</AntdRegistry>
        </LoadingProvider>
      </body>
    </html>
  )
}
