import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import './globals.css'
import { AntdRegistry } from '@ant-design/nextjs-registry'
import dynamic from 'next/dynamic'
import { LoadingProvider } from './context/LoadingContext'
import RefreshToken from './(auth)/_component/RefreshToken'
import { StoreProvider } from './redux/StoreProvider'

const GlobalLoading = dynamic(() => import('@/components/GlobalLoading'), { ssr: false })

const inter = Nunito({ subsets: ['vietnamese'], weight: ['400', '500', '700', '900'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <head>
        <link rel='icon' href='/favicon.ico' />
      </head>
      <body className={inter.className}>
        <StoreProvider>
          <AntdRegistry>
            <LoadingProvider>
              <GlobalLoading />
              <RefreshToken />
              {children}
            </LoadingProvider>
          </AntdRegistry>
        </StoreProvider>
      </body>
    </html>
  )
}
